[package]
name = "niklang"
version = "0.1.0"
edition = "2024"


[dependencies]
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.38", features = ["full"] }
rustyline = "13"


[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
overflow-checks = true
debug = false
strip = true
